# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
    - id: tagbased_version_updater
      name: TagBased_Version_Updater
      entry: python -m tools.auto_version_updater
      language: system
      types: [python]
      verbose: true
  - repo: https://github.com/pdm-project/pdm
    rev: 2.17.3
    hooks:
      - id: pdm-export
        args: ['-o', 'requirements.txt', '--prod', '--without-hashes']
        files: ^pdm.lock$
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.12
