# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pdm-project/pdm
    rev: 2.17.3
    hooks:
      - id: pdm-export
        args: ['-o', 'requirements.txt', '--prod', '--without-hashes']
        files: ^pdm.lock$
